# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://PrinceJavierDQ.github.io/test/"

git_url = "https://github.com/PrinceJavierDQ/test/tree/main/"

def custom_doc_links(name): return None
